aai_vehicles = true
require("prototypes/styles")
require("prototypes/technology/technology")
require("prototypes/entity/entity")
require("prototypes/entity/entity-structures")
require("prototypes/entity/entity-deployer")
require("prototypes/entity/entity-depot")
require("prototypes/entity/projectiles")
require("prototypes/recipe/recipe")
require("prototypes/recipe/ammo")
require("prototypes/item/item")
require("prototypes/item/ammo")
require("prototypes/item-groups")
